# Generated by Django 4.0.2 on 2022-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_autor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
