# Generated by Django 4.0.2 on 2022-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_alter_libro_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateTimeField(verbose_name='Fecha de publicación'),
        ),
    ]
