# Generated by Django 4.0.2 on 2022-04-12 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_alter_libro_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='hora_creacion',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de creación'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(verbose_name='Fecha de publicación'),
        ),
    ]
