# Generated by Django 4.0.2 on 2022-04-12 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_libro_hora_creacion_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='hora_creacion',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Hora de creación'),
        ),
    ]
