# Generated by Django 4.0.2 on 2022-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_alter_libro_hora_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='hora_creacion',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de creación'),
        ),
    ]
