# Generated by Django 4.0.2 on 2022-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0009_alter_libro_hora_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='hora_creacion',
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateTimeField(verbose_name='Fecha de publicación'),
        ),
    ]
