# Generated by Django 4.0.2 on 2022-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0010_remove_libro_hora_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_desplegar',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='hora_creacion',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de creación'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(verbose_name='Fecha de publicación'),
        ),
    ]
