# Generated by Django 4.0.2 on 2022-04-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0011_libro_fecha_desplegar_libro_hora_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_desplegar',
        ),
        migrations.AlterField(
            model_name='libro',
            name='hora_creacion',
            field=models.TimeField(null=True, verbose_name='Hora de creación'),
        ),
    ]
