# Generated by Django 4.0.2 on 2022-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0013_alter_libro_hora_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateTimeField(verbose_name='Fecha de publicación'),
        ),
    ]
