# Generated by Django 4.0.2 on 2022-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0014_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(verbose_name='Fecha de publicación'),
        ),
    ]
