# Generated by Django 4.0.2 on 2022-04-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0016_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='hora_creacion',
        ),
    ]
