# Generated by Django 4.0.2 on 2022-04-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0017_remove_libro_hora_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['id'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
